name: Python-helloworld
on:
  push:
    branches:
      - main
      - develop
    pull_request:
      branches:
        - main

jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python --version
